### ISSUE TITLE
Нужен общий метод определения атрибута элемента

### ISSUE THREAD

**Issue by mismikka** [Aurococcus/wasd#6]

**Comment by Aurococcus** [comment]
Не понимаю, что нужно. Есть `grab_attribute_from`:

``<span id="tooltip" title="hello_world"> </span>``

```
>>> browser.grab_attribute_from(Element('#tooltip'), 'title')
"hello_world"
```

Это то, что нужно?

**Comment by mismikka** [comment]
Нужен метод, который бы проверял наличие атрибута для элемента и возвращал true, если атрибут найден, и false, если атрибут отсутствует.
